### ISSUE TITLE
Support for video streaming

### ISSUE THREAD

**Issue by jwalitptl** [realtime-ai/openai-realtime-webrtc-go#2]
Hey there! I been seeing many example for audio streaming but havent found anything for video & audio streaming.Love to see that feature added.

**Comment by notedit** [comment]
openai does not support video yet.

**Comment by jwalitptl** [comment]
My use case is I just want to get video stream and do facial expressions detection using CNN while OpenAI voice api is to do conversation only. I think it can be done just setting up video track in pion webrtc.
